if ROLE in('INPUT', 'REJECTED') then do;
if upcase(NAME) in(
'IMP_RUNTIME'
'IMP_SS_MEAN'
'R'
'GENRE_ANIMATIONMANGA'
'GENRE_DRAMATELE'
'GENRE_FITNESSSPORTS'
'GENRE_HISTDOCUMENT'
'GENRE_HORROR'
'GENRE_SCI_FI'
'GENRE_THRILLMYSSUSP'
'TOMATOMETER_COUNT'
) then ROLE='INPUT';
else do;
ROLE='REJECTED';
COMMENT = "Reg2: Rejected using stepwise selection";
end;
end;
